version: "3.9"

services:
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    volumes:
      - "~/test/frontend:/data"
  backend:
    build: backend
    ports:
      - "1039:1039"
    volumes:
      - "~/test/backend:/data"
    environment:
      - OBJECTSERVER_KEY
  objectserver1:
    build: objectserver
    volumes:
      - "~/test/objectserver1:/data"
    environment:
      - OBJECTSERVER_KEY
  objectserver2:
    build: objectserver
    volumes:
      - "~/test/objectserver2:/data"
    environment:
      - OBJECTSERVER_KEY
  objectserver3:
    build: objectserver
    volumes:
      - "~/test/objectserver3:/data"
    environment:
      - OBJECTSERVER_KEY
  objectserver4:
    build: objectserver
    volumes:
      - "~/test/objectserver4:/data"
    environment:
      - OBJECTSERVER_KEY
  objectserver5:
    build: objectserver
    volumes:
      - "~/test/objectserver5:/data"
    environment:
      - OBJECTSERVER_KEY
  objectserver6:
    build: objectserver
    volumes:
      - "~/test/objectserver6:/data"
    environment:
      - OBJECTSERVER_KEY
