version: "3.9"

services:
  frontend:
    image: "ghcr.io/kaichiachen/policy-driven-data-protection-frontend:master"
    ports:
      - "3000:3000"
  backend:
    image: "ghcr.io/kaichiachen/policy-driven-data-protection-backend:master"
    ports:
      - "1039:1039"
  fileserver1:
    image: "ghcr.io/kaichiachen/policy-driven-data-protection-fileserver:master"
    ports:
      - "1040:1040"
  fileserver2:
    image: "ghcr.io/kaichiachen/policy-driven-data-protection-fileserver:master"
    ports:
      - "1041:1040"
  fileserver3:
    image: "ghcr.io/kaichiachen/policy-driven-data-protection-fileserver:master"
    ports:
      - "1042:1040"
