version: "3.9"

services:
  frontend:
    image: "ghcr.io/kaichiachen/policy-driven-data-protection-frontend:master"
    ports:
      - "3000:3000"
  backend:
    image: "ghcr.io/kaichiachen/policy-driven-data-protection-backend:master"
    ports:
      - "1039:1039"
    environment:
      - OBJECTSERVER_KEY
  objectserver1:
    image: "ghcr.io/kaichiachen/policy-driven-data-protection-objectserver:master"
    environment:
      - OBJECTSERVER_KEY
  objectserver2:
    image: "ghcr.io/kaichiachen/policy-driven-data-protection-objectserver:master"
    environment:
      - OBJECTSERVER_KEY
  objectserver3:
    image: "ghcr.io/kaichiachen/policy-driven-data-protection-objectserver:master"
    environment:
      - OBJECTSERVER_KEY
  objectserver4:
    image: "ghcr.io/kaichiachen/policy-driven-data-protection-objectserver:master"
    environment:
      - OBJECTSERVER_KEY
  objectserver5:
    image: "ghcr.io/kaichiachen/policy-driven-data-protection-objectserver:master"
    environment:
      - OBJECTSERVER_KEY
  objectserver6:
    image: "ghcr.io/kaichiachen/policy-driven-data-protection-objectserver:master"
    environment:
      - OBJECTSERVER_KEY
