version: "3.9"

services:
  frontend:
    image: "ghcr.io/kaichiachen/policy-driven-data-protection-frontend:master"
    ports:
      - "3000:3000"
  backend:
    image: "ghcr.io/kaichiachen/policy-driven-data-protection-backend:master"
    ports:
      - "1039:1039"
  objectserver1:
    image: "ghcr.io/kaichiachen/policy-driven-data-protection-objectserver:master"
    ports:
      - "1040:1040"
  objectserver2:
    image: "ghcr.io/kaichiachen/policy-driven-data-protection-objectserver:master"
    ports:
      - "1041:1040"
  objectserver3:
    image: "ghcr.io/kaichiachen/policy-driven-data-protection-objectserver:master"
    ports:
      - "1042:1040"
  objectserver4:
    image: "ghcr.io/kaichiachen/policy-driven-data-protection-objectserver:master"
    ports:
      - "1043:1040"
  objectserver5:
    image: "ghcr.io/kaichiachen/policy-driven-data-protection-objectserver:master"
    ports:
      - "1044:1040"
  objectserver6:
    image: "ghcr.io/kaichiachen/policy-driven-data-protection-objectserver:master"
    ports:
      - "1045:1040"
