version: "3.9"

services:
  frontend:
    build: frontend
    ports:
      - "3000:3000"
  backend:
    build: backend
    ports:
      - "1039:1039"
  objectserver1:
    build: objectserver
    ports:
      - "1040:1040"
  objectserver2:
    build: objectserver
    ports:
      - "1041:1040"
  objectserver3:
    build: objectserver
    ports:
      - "1042:1040"
